server:
  port: 8080
#一般测试环境是8080

spring:
  datasource:
    url: jdbc:mysql://192.144.131.25:3306/jddb?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: zhao123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: org.lanqiao.jd.entity
  mapper-locations: classpath:mapping/*Mapper.xml




#showSql
logging:
  level:
    com:
      example:
        mapper : debug